myproject/urls.py
from django.contrib import admin
from django.urls import include, path, reverse
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='sso_ui:home'), name='index'),
    path('admin/', admin.site.urls),
    path('sso/', include('sso_ui.urls')),
]

sso_ui/urls.py
"""SSO UI urls module."""
from django.urls import path
from django_cas_ng import views as cas_views

from . import views

app_name = 'sso_ui'
urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('login/', cas_views.LoginView.as_view(), name='login'),
    path('logout/', cas_views.LogoutView.as_view(), name='logout'),
]

sso_ui/models.py
"""SSO UI models module."""
import json

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_cas_ng.signals import cas_user_authenticated

LANG = settings.SSO_UI_ORG_DETAIL_LANG
ORG_CODE = {}
with open(settings.SSO_UI_ORG_DETAIL_FILE_PATH, 'r') as ORG_CODE_FILE:
    ORG_CODE.update(json.load(ORG_CODE_FILE))


class Profile(models.Model):
    """User Profile model."""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    org_code = models.CharField('kode organisasi', max_length=11, blank=True)
    role = models.CharField('peran pengguna', max_length=128, blank=True)
    npm = models.CharField('Nomor Pokok Mahasiswa', max_length=10, blank=True)
    faculty = models.CharField('fakultas', max_length=128, blank=True)
    study_program = models.CharField('program studi', max_length=128, blank=True)
    educational_program = models.CharField('program pendidikan', max_length=128, blank=True)

    class Meta:
        verbose_name = 'profil'
        verbose_name_plural = verbose_name

    def __str__(self):
        """Return username of the user."""
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(instance, created, **kwargs):
    """Create user profile if user object was just created."""
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(instance, **kwargs):
    """Save user profile post user save."""
    instance.profile.save()


@receiver(cas_user_authenticated)
def save_user_attributes(user, attributes, **kwargs):
    """Save user attributes from CAS into user and profile objects."""
    user.save()
    profile = user.profile
    profile.role = attributes['peran_user']
    profile.npm = attributes['npm']
    if profile.role == 'mahasiswa':
        user.email = f'{user.username}@ui.ac.id'

    full_name = attributes['nama']
    i = full_name.rfind(' ')
    user.first_name, user.last_name = full_name[:i], full_name[i + 1:]

    org_code = attributes['kd_org']
    record = ORG_CODE[LANG][org_code]
    profile.org_code = org_code
    profile.faculty = record['faculty']
    profile.study_program = record['study_program']
    profile.educational_program = record['educational_program']

    user.save()

sso_ui/views.py
"""SSO UI views module."""
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


def home(request):
    """Render home page."""
    return render(request, "sso_ui/home.html")


@login_required(login_url='sso_ui:login')
def profile(request):
    """Render profile page."""
    context = {
        "profile": {
            "Nama lengkap": request.user.get_full_name(),
            "Nama pengguna": request.user.username,
            "Alamat surel": request.user.email,
            "Kode organisasi": request.user.profile.org_code,
            "Peran pengguna": request.user.profile.role,
            "Nomor Pokok Mahasiswa": request.user.profile.npm,
            "Fakultas": request.user.profile.faculty,
            "Jurusan": request.user.profile.study_program,
            "Program pendidikan": request.user.profile.educational_program
        }
    }
    return render(request, "sso_ui/profile.html", context)

sso_ui/templates/sso_ui/home.html
{% extends 'myproject/base.html'%}

{% block navbar %}
{% with current_nav='home' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block main_container %}
  {% with vertical_center=True %}
    {{ block.super }}
  {% endwith %}
{% endblock main_container %}

{% block title %}{{ block.super }} - Beranda{% endblock title %}

{% block content %}
<div id="home-header">
  <h1 class="display-3 text-center font-weight-bold m-auto">
    {% if not user.is_authenticated %}
    <a href="{% url 'sso_ui:login' %}" class="no-deco text-primary">Masuk dengan SSO UI</a>
    {% else %}
    <a href="{% url 'sso_ui:logout' %}" class="no-deco text-primary">Keluar dari SSO UI</a>
    {% endif %}
  </h1>
</div>
{% endblock content %}

sso_ui/templates/sso_ui/profile.html
{% extends 'myproject/base.html' %}

{% block navbar %}
{% with current_nav='profile' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block title %}{{ block.super }} - Profil{% endblock title %}

{% block content %}
<div class="py-3"></div>
<div id="home-header" class="px-2">
  <h1 class="display-4 p-3 text-info">Profil</h1>
</div>
<div id="profile-table" class="table-responsive mw-75 mt-4 mx-auto">
  <table class="table table-hover">
    <tbody>
      {% for key, value in profile.items %}
        <tr>
          <th>{{ key }}</th>
            <td>{{ value }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

templates/components/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
{% block custom_meta %}
{% endblock custom_meta %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="{% static "css/style.css" %}">
{% block custom_styles %}
{% endblock custom_styles %}
<title>{% block title %}myproject{% endblock title %}</title>

templates/components/navbar.html
<a class="navbar-brand" href="{% url 'index' %}">myproject</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse order-1 order-md-0 dual-collapse" id="collapsibleNavbar">
  {% block navbar_contents %}
  <ul class="navbar-nav mr-auto">
    <li class="nav-item mx-2">
      <a class="nav-link{% if current_nav == 'home' %} font-weight-bold text-light{% endif %}" href="{% url 'sso_ui:home' %}">Beranda</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item mx-2">
      <a class="nav-link{% if current_nav == 'profile' %} font-weight-bold text-light{% endif %}" href="{% url 'sso_ui:profile' %}">Profil</a>
    </li>
    {% endif %}
    <li class="nav-item mx-2">
      <a class="nav-link" href="https://github.com/anakpacil/sso-ui-starter-django">Repo GitHub</a>
    </li>
  </ul>
  {% endblock navbar_contents%}
</div>

templates/myproject/base.html
{% load static %}
<!doctype html>
<html>
  <head>
    {% include 'components/head.html' %}
  </head>
  <body>
    <nav class="navbar navbar-expand-md fixed-top bg-dark navbar-dark">
      {% block navbar %}
        {% include 'components/navbar.html' %}
      {% endblock navbar %}
    </nav>
    {% block main_container %}
      <div class="container m-auto{% if vertical_center %} d-flex h-100 align-items-center{% endif %}">
      <main role="main" class="w-100">
          {% block content %}
          {% endblock content %}
      </main>
      </div>
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block custom_scripts %}
    {% endblock custom_scripts %}
  </body>
</html>